main: com.cavetale.skills.SkillsPlugin
name: Skills
version: 0.1
api-version: 1.13
description: Skills Plugin
author: StarTux
website: https://cavetale.com
depend: [WorldMarker, SQL, GenericEvents, Exploits]
softdepend: []
commands:
  skills:
    aliases: [skill, sk]
    description: Skills Command
    permission: skills.skills
    usage: |-
      /sk mining - Mining skill info
      /sk farming - Farming skill info
      /sk combat - Combat skill info
      /sk talent - Talent tree
      /sk list - List skills and talents
      /sk info - Info pages
      /sk hi - Highscore
  skadmin:
    aliases: [skadm, skilladmin, skillsadmin]
    description: Skills admin interface
    permission: skills.admin
    usage: |-
      /skadm reloadadvancements
      /skadm gime - Give yourself a talent point
      /skadm particles - Toggle particles
      /skadm median - Display median skill points
      /skadm give <player> <skill> <points>
permissions:
  skills.skills:
    description: Use /skills
    default: false
  skills.admin:
    description: Use /skadmin
    default: op